language: node_js
node_js: node_js
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: PcG7h9s+CrgzuXlz6yabm1oBT5i100TB3TXDXFiF0xK0sQ/vcVdVHHOHC6G5eK7cY8gTUaUWXND80H3mMIvd/iVTbfaWiGymen2DKMKgoGqS8fIsPB7IaZ+29HHoii2IadBQ3neTesNCOVpzZ3U7dd0aGR2PHNN+dBfnCfN90joNQt3CD7LMtD1kfQqlZxOHUtNGkaj4y+FrvI8UVH5U7k65/RBUirKItFMPmDbGTgg8YuFMq63ouPzZLHRU5TlymRH33FY6MaIqEGg4Et2qtlvx68liyCrFd+aOS8KtafDuokkFGtizU1tZ26VIUrgxp2/XpEwB/bqVeuRgJnZe+J/nUStuEZjkWCx/KLnMeMg0Gkbtn+DJe1VJqL70XRNPOD5RvNOh6/V5UGoXP9HBmBm8vYcYyQCs+3NxTB0BC3LBATKZc1i8v6LEVemgMrzgtx+95aYsz5b2UhfdiJ4V0+e3PPS1T/9r/Lo64DUAUExseAIJbOVdfPcIw1V9wMARPKzBo1vsmWkIOlvqVFzOKHe7RwFkHQe5C5sNue+9HkM0+PT+l2ec+AA48sctF9u8sKUsh1UiRPogDrLKIj/9bn2WkfhoxFsHG7syXhB6yMIUQWt6qaxNdY4uJzh4emucs+F0L0rSA6NUQaQ2LQU/8PwiET+PAml8cRFowC5eHLc=
